project_name: godo

builds:
  - binary: godo
    main: .
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

# Use default archive formats (zip on Windows, tar.gz on *nix)

changelog:
  use: git
